CREATE TABLE Account(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    NAME VARCHAR(20) NOT NULL UNIQUE ,
    PASSWORD VARCHAR(256) not null,
    `RANK` VARCHAR(8)
);

INSERT INTO account(NAME, PASSWORD, `RANK`)
    VALUE("ADMIN", 1234, "ADMIN")
